---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.22.22.21-172.22.22.30
  METALLB_K8S_GATEWAY_ADDR: 172.22.22.21
  METALLB_TRAEFIK_ADDR: 172.22.22.22
