# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kErbjG2Xwwrf,iv:ppT9Sf0ZHodqiergmD0tuUpipx3CWGD9CeLPutX9U2M=,tag:UHK0LDAtznef0s8no+atNQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gkhlr6HNwWLK8Gh3Dx2S/lIH,iv:QshFglW6E+6cepgK1XwEgd59IK0bKeSYlDegGfXWHnA=,tag:tRKyP5DzMPenLBB8ztJaXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ektnty768fg3wmhhepcg760zvxspclsd0qkfxa2f9ly8fgslyausrasx94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ2h0cTFOa21aR0FxajVm
            NFRPR2tnMytLR0Rkc2RIZllMT3FYenl2dWc4Ckg3NGpYMnVoWWIyV1N1TmwyOHJT
            RmxBNUJ6Z1hjZ1hyQzVqTmg1b085NFkKLS0tIGxrcXNiWDB3SUdNN2ErZFlqVk0v
            VlJWMzNSZVVCcFlBMXhvV0s2ZVJub2MKcCJwT/S2AAm/YQuVpqGUR/mGVbKxv0zT
            iuYHdBH4hs6E8tPooXiUgiajJugDtJWkzA+JMzH8LnTIjoq/WU3hyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T22:10:39Z"
    mac: ENC[AES256_GCM,data:ZWzfav1xbXwdQqFyXwKjvx0QNISIGyKAvJdaB4CCE7Qb21Hvxq1BLpjycrgwiHEnHsLzsBOuii69q/sPlGYiaYtsueIuEQqvSdbGN5cDwfMoHDGH0BEOvsNud5K8gYqbryJ10W4zJISE1oJatcW3raXQ222/R8SemVyEYP1beWY=,iv:p5qdKQ0Q3deQczouQH5hmGIH502U447Ua2pYd01s+D8=,tag:oW+HGYVWEkx8sBiicZ/wdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
